# Generated by Django 5.1.7 on 2025-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
