# Generated by Django 5.1.7 on 2025-10-22 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_alter_affiliate_commission_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
