# Generated by Django 5.1.7 on 2025-10-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_alter_affiliate_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='pix_key',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
