# Generated by Django 5.1.7 on 2025-10-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_alter_affiliate_pix_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='code',
            field=models.CharField(blank=True, max_length=26, unique=True),
        ),
    ]
